//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ptc.Data.Condition2.DataBase.MSSQL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Announcement
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Announcement()
        {
            this.BranchCounter = new HashSet<BranchCounter>();
            this.MachineType = new HashSet<MachineType>();
        }
    
        public int ID { get; set; }
        public string Title { get; set; }
        public string Content { get; set; }
        public string PreviewImagePath { get; set; }
        public string ContentImagePath { get; set; }
        public Nullable<int> TopMost { get; set; }
        public System.DateTime PostStartDate { get; set; }
        public System.DateTime PostEndDate { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string NoticeType { get; set; }
        public string NoticeTarget { get; set; }
        public string CustomizeNoticeUser { get; set; }
        public string removeUserID { get; set; }
        public System.DateTime UpdateDate { get; set; }
        public bool IsPerformance { get; set; }
        public bool hasPushed { get; set; }
        public bool IsPubilc { get; set; }
        public string DescriptionOfAddress { get; set; }
        public bool DescriptionOfAddressIsURL { get; set; }
        public byte AnnouncementType { get; set; }
    
        public virtual Coupon Coupon { get; set; }
        public virtual Course Course { get; set; }
        public virtual Lottery Lottery { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BranchCounter> BranchCounter { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MachineType> MachineType { get; set; }
    }
}
