//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ptc.Data.Condition2.DataBase.MSSQL
{
    using System;
    using System.Collections.Generic;
    
    public partial class BranchCounter
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BranchCounter()
        {
            this.Announcement = new HashSet<Announcement>();
            this.Coupon = new HashSet<Coupon>();
            this.Lottery = new HashSet<Lottery>();
        }
    
        public int BranchCounterID { get; set; }
        public string BranchCounterName { get; set; }
        public string TelephoneArea { get; set; }
        public string Telephone { get; set; }
        public bool IsEnable { get; set; }
        public int AddressCityID { get; set; }
        public string AddressArea { get; set; }
        public string Address { get; set; }
        public string TradingTime1 { get; set; }
        public string TradingTime2 { get; set; }
        public string TradingTime3 { get; set; }
        public string TransporInfo { get; set; }
        public string ImgUrl { get; set; }
        public double Longitude { get; set; }
        public double Latitude { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
    
        public virtual CityList CityList { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Announcement> Announcement { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Coupon> Coupon { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Lottery> Lottery { get; set; }
    }
}
