//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ptc.Data.Condition2.DataBase.MSSQL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Coupon
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Coupon()
        {
            this.CouponSN = new HashSet<CouponSN>();
            this.UserCoupon = new HashSet<UserCoupon>();
            this.BranchCounter = new HashSet<BranchCounter>();
        }
    
        public Nullable<int> CouponCount { get; set; }
        public int CurrentCount { get; set; }
        public Nullable<int> DiscountAmount { get; set; }
        public Nullable<decimal> DiscountPercentage { get; set; }
        public System.DateTime ExchangeStartDate { get; set; }
        public System.DateTime ExchangeEndDate { get; set; }
        public Nullable<int> LimitAmountOfPurchase { get; set; }
        public string LimitOther { get; set; }
        public int AnnouncementID { get; set; }
        public Nullable<System.DateTime> ActiveStartDate { get; set; }
        public Nullable<System.DateTime> ActiveEndDate { get; set; }
        public string DescriptionOfUse { get; set; }
        public string DescriptionOfOther { get; set; }
    
        public virtual Announcement Announcement { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CouponSN> CouponSN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserCoupon> UserCoupon { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BranchCounter> BranchCounter { get; set; }
    }
}
