//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ptc.Data.Condition2.DataBase.MSSQL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CourseLocations
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CourseLocations()
        {
            this.UserCourseLocation = new HashSet<UserCourseLocation>();
        }
    
        public int AnnouncementID { get; set; }
        public int SessionID { get; set; }
        public int LocationID { get; set; }
        public int LimitCompanionCount { get; set; }
        public int LimitPersonCount { get; set; }
        public bool IsEnable { get; set; }
        public Nullable<int> BranchCounterID { get; set; }
        public string BranchCounterName { get; set; }
        public int BranchCounterCityID { get; set; }
        public string BranchCounterCityName { get; set; }
        public string BranchCounterAddress { get; set; }
        public int NowActiveCount { get; set; }
    
        public virtual CourseSession CourseSession { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserCourseLocation> UserCourseLocation { get; set; }
    }
}
