//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ptc.Data.Condition2.DataBase.MSSQL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HLHApp_DemoEntities : DbContext
    {
        public HLHApp_DemoEntities()
            : base("name=HLHApp_DemoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Announcement> Announcement { get; set; }
        public virtual DbSet<Arguments> Arguments { get; set; }
        public virtual DbSet<AspNetRoles> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaims> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogins> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUsers> AspNetUsers { get; set; }
        public virtual DbSet<BranchCounter> BranchCounter { get; set; }
        public virtual DbSet<CityList> CityList { get; set; }
        public virtual DbSet<Coupon> Coupon { get; set; }
        public virtual DbSet<CouponSN> CouponSN { get; set; }
        public virtual DbSet<Course> Course { get; set; }
        public virtual DbSet<CourseLocations> CourseLocations { get; set; }
        public virtual DbSet<CourseSession> CourseSession { get; set; }
        public virtual DbSet<Lottery> Lottery { get; set; }
        public virtual DbSet<MachineType> MachineType { get; set; }
        public virtual DbSet<SendBackReason> SendBackReason { get; set; }
        public virtual DbSet<ShopChannel> ShopChannel { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<User> User { get; set; }
        public virtual DbSet<UserCoupon> UserCoupon { get; set; }
        public virtual DbSet<UserCourseLocation> UserCourseLocation { get; set; }
        public virtual DbSet<UserProductWarranty> UserProductWarranty { get; set; }
    }
}
