//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ptc.Data.Condition2.DataBase.MSSQL
{
    using System;
    using System.Collections.Generic;
    
    public partial class MachineType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MachineType()
        {
            this.UserProductWarranty = new HashSet<UserProductWarranty>();
            this.Announcement = new HashSet<Announcement>();
        }
    
        public string MachineTypeID { get; set; }
        public string BrandID { get; set; }
        public string MachineSerialCodeImagePath { get; set; }
        public string ProductImagePath { get; set; }
        public string BrandName { get; set; }
        public string MachineTypeName { get; set; }
        public string MachineSerialCodeDescription { get; set; }
        public string ShopSuppliesURL { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserProductWarranty> UserProductWarranty { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Announcement> Announcement { get; set; }
    }
}
