//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ptc.Data.Condition2.DataBase.MSSQL
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserCourseLocation
    {
        public int AnnouncementID { get; set; }
        public int SessionID { get; set; }
        public int LocationID { get; set; }
        public string AccountName { get; set; }
        public System.DateTime GetDateTime { get; set; }
        public int LimitPersonCount { get; set; }
        public bool IsEnable { get; set; }
        public long CourseSNID { get; set; }
        public string RegisteInfoHistory { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
    
        public virtual CourseLocations CourseLocations { get; set; }
        public virtual User User { get; set; }
    }
}
