//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ptc.Data.Condition2.DataBase.MSSQL
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserCoupon
    {
        public Nullable<System.DateTime> GetDateTime { get; set; }
        public bool Invalid { get; set; }
        public Nullable<System.DateTime> UseDateTime { get; set; }
        public string AccountName { get; set; }
        public int AnnouncementID { get; set; }
        public Nullable<long> CouponSNID { get; set; }
    
        public virtual Coupon Coupon { get; set; }
        public virtual CouponSN CouponSN { get; set; }
        public virtual User User { get; set; }
    }
}
