//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ptc.Data.Condition2.DataBase.MSSQL
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User()
        {
            this.UserCoupon = new HashSet<UserCoupon>();
            this.UserCourseLocation = new HashSet<UserCourseLocation>();
            this.UserProductWarranty = new HashSet<UserProductWarranty>();
        }
    
        public string AccountName { get; set; }
        public string PhoneVaildCode { get; set; }
        public Nullable<System.DateTime> PhoneVaildCodeDate { get; set; }
        public int DailyPhoneVaildCount { get; set; }
        public string ResetPasswordCode { get; set; }
        public Nullable<System.DateTime> ResetPasswordDate { get; set; }
        public int DailyResetPasswordCodeCount { get; set; }
        public string RegistrationID { get; set; }
        public Nullable<bool> IsVaildPhone { get; set; }
        public string UserInfoVersion { get; set; }
        public Nullable<int> ResetPasswordCount { get; set; }
        public Nullable<int> PhoneVaildCount { get; set; }
        public Nullable<int> MobileDevice { get; set; }
        public string UserName { get; set; }
        public string Phone { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserCoupon> UserCoupon { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserCourseLocation> UserCourseLocation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserProductWarranty> UserProductWarranty { get; set; }
    }
}
